### PR TITLE
Use the Ace editor

### LINKED ISSUE #6: We cannot add code-editor to this project
It uses a GPL license while this uses Apache. You cannot include a GPL project in an Apache project.

### PR DESCRIPTION
**Pull request by piperswe**
It does everything code-editor did, but it's under the BSD license.

Fixes #6

### CODE REVIEW

**Comment by piperswe** [comment]
Erm... I'm not sure what the conflicts are but I'll get right on fixing those.

**Comment by piperswe** [comment]
There we go.

**Comment by piperswe** [comment]
Just a few people use Ace: https://ace.c9.io/#nav=production

**Comment by ztaylor54** [comment]
I'm convinced.

**Pull request merged**
