### PR TITLE
Create a React "Hello, world!" project

### PR DESCRIPTION
**Pull request by piperswe**
I believe this should be built on React as opposed to Angular, as it would better suit both our programming preferences (pure functional components!) and performance.

### CODE REVIEW

**Comment by piperswe** [comment]
Umm, seems like my Markdown autoformatter went to town on the contributing instructions. I'll fix that in a minute. Do not merge yet.

**Comment by piperswe** [comment]
Alright, once checks complete ready to merge.

**Comment by piperswe** [comment]
@ztaylor54 Have you even glanced over this code?

(psstt: there are only actually 22 lines of code in this commit. The rest is documentation and `package.json`)

**Comment by piperswe** [comment]
PINGING @ztaylor54

**Review by ztaylor54 — APPROVED** [review]
Sorry for taking so long. College is stressful!

**Pull request merged**
